import { useState } from "react";
import { createModuleRoute } from "@/core/routes/createModuleRoute";
import { useHasCapability } from "@/core/roles/hooks";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCents } from "@/core/money";
import {
  useIntelligenceOpportunities,
  useIntelligenceRecommendations,
  useIntelligenceRepository,
  useObservations,
  usePeriod,
} from "@/modules/intelligence/hooks";

export const Route = createModuleRoute("/intelligence/findings")({
  moduleId: "intelligence",
  head: () => ({
    meta: [
      { title: "Optimization Findings — Skild OS" },
      {
        name: "description",
        content:
          "Deterministic observations, opportunities and recommendations derived from the shop's own records.",
      },
      { property: "og:title", content: "Optimization Findings — Skild OS" },
      {
        property: "og:description",
        content:
          "Evidence-backed findings a human reviews and accepts — Skild never acts on them by itself.",
      },
    ],
  }),
  component: FindingsPage,
});

function FindingsPage() {
  const repo = useIntelligenceRepository();
  const period = usePeriod(30);
  const canRead = useHasCapability("intelligence.read");
  const canOptimize = useHasCapability("intelligence.optimize");
  const canRecommend = useHasCapability("intelligence.recommend");

  const { data: observations, refresh: refreshObs } = useObservations();
  const { data: opportunities, refresh: refreshOpp } = useIntelligenceOpportunities();
  const { data: recommendations, refresh: refreshRec } = useIntelligenceRecommendations();

  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | undefined>();

  async function runOptimization() {
    setBusy(true);
    setError(undefined);
    try {
      await repo.runOptimization(period);
      refreshObs();
      refreshOpp();
      refreshRec();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  if (!canRead) {
    return (
      <p className="text-sm text-muted-foreground">
        You do not have permission to view optimization findings.
      </p>
    );
  }

  return (
    <div className="space-y-8">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Findings</h1>
          <p className="text-xs text-muted-foreground">
            Findings are generated by fixed rules over stored records. Each one
            cites the records it came from, and none of them change anything on
            their own.
          </p>
        </div>
        {canOptimize && (
          <Button size="sm" onClick={runOptimization} disabled={busy}>
            {busy ? "Analysing…" : "Run analysis"}
          </Button>
        )}
      </header>

      {error && <p className="text-sm text-destructive">{error}</p>}

      <section>
        <h2 className="mb-2 text-sm font-medium">Observations</h2>
        {observations.length === 0 ? (
          <p className="text-xs text-muted-foreground">
            No observations yet. Run an analysis to generate them.
          </p>
        ) : (
          <ul className="space-y-3">
            {observations.map((o) => (
              <li key={o.id} className="rounded-lg border p-3">
                <div className="flex items-start justify-between gap-2">
                  <span className="text-sm font-medium">{o.title}</span>
                  <Badge variant="secondary" className="text-[10px]">
                    {o.severity}
                  </Badge>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{o.detail}</p>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  Evidence: {o.evidence.kind} ·{" "}
                  {o.evidence.sources.length} record(s)
                </p>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section>
        <h2 className="mb-2 text-sm font-medium">Opportunities</h2>
        {opportunities.length === 0 ? (
          <p className="text-xs text-muted-foreground">
            No opportunities identified.
          </p>
        ) : (
          <ul className="space-y-3">
            {opportunities.map((o) => (
              <li key={o.id} className="rounded-lg border p-3">
                <div className="flex items-start justify-between gap-2">
                  <span className="text-sm font-medium">{o.title}</span>
                  <span className="text-xs tabular-nums text-muted-foreground">
                    {o.estimatedValueCents === null
                      ? "value unknown"
                      : formatCents(o.estimatedValueCents)}
                  </span>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{o.detail}</p>
                {o.estimatedValueCents === null && (
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    No value is shown because the records do not support one.
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      <section>
        <h2 className="mb-2 text-sm font-medium">Recommendations</h2>
        {!canRecommend ? (
          <p className="text-xs text-muted-foreground">
            You do not have permission to view recommendations.
          </p>
        ) : recommendations.length === 0 ? (
          <p className="text-xs text-muted-foreground">
            No recommendations. Nothing in the records justifies one.
          </p>
        ) : (
          <ul className="space-y-3">
            {recommendations.map((r) => (
              <li key={r.id} className="rounded-lg border p-3">
                <div className="flex items-start justify-between gap-2">
                  <span className="text-sm font-medium">{r.title}</span>
                  <Badge variant="outline" className="text-[10px]">
                    {r.status}
                  </Badge>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{r.rationale}</p>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  Suggested action: {r.suggestedAction} — a person must carry
                  this out; Skild OS will not.
                </p>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
