import { Link, useNavigate } from "@tanstack/react-router";
import { Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { createModuleRoute } from "@/core/routes/createModuleRoute";
import { useHasCapability } from "@/core/roles/hooks";
import { useLeads, useLeadsNeedingAttention } from "@/modules/marketing/hooks";
import { formatDenver } from "@/modules/communication/data/time";

export const Route = createModuleRoute("/leads/")({
  moduleId: "marketing",
  head: () => ({
    meta: [
      { title: "Lead Pipeline — Skild OS" },
      {
        name: "description",
        content:
          "The Skild Auto lead pipeline: stage, source, score, and who is waiting on whom.",
      },
      { property: "og:title", content: "Lead Pipeline — Skild OS" },
      {
        property: "og:description",
        content:
          "See every open lead, its attribution, and the follow-ups that are due.",
      },
    ],
  }),
  component: LeadsIndex,
});

function LeadsIndex() {
  const navigate = useNavigate();
  const { data: leads, loading } = useLeads();
  const { data: attention } = useLeadsNeedingAttention();
  const canRead = useHasCapability("leads.read");
  const canWrite = useHasCapability("leads.write");

  if (!canRead) {
    return (
      <p className="p-6 text-sm text-muted-foreground">
        You do not have permission to view leads.
      </p>
    );
  }

  const attentionIds = new Set(attention.map((a) => a.leadId));

  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-6">
      <header className="mb-4 flex flex-wrap items-center justify-between gap-2">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Leads</h1>
          <p className="text-xs text-muted-foreground">
            {leads.length} recorded · {attention.length} need attention
          </p>
        </div>
        {canWrite && (
          <Button onClick={() => navigate({ to: "/leads/new" })}>
            <Plus className="mr-1 h-4 w-4" /> Record lead
          </Button>
        )}
      </header>

      {loading ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : leads.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          No leads recorded yet. Leads are captured by hand or by a future
          integration adapter — none are ever generated by the system.
        </p>
      ) : (
        <ul className="space-y-2">
          {leads.map((l) => (
            <li
              key={l.id}
              className="rounded-md border border-border p-3 text-sm"
            >
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div className="min-w-0">
                  <Link
                    to="/leads/$leadId"
                    params={{ leadId: l.id }}
                    className="font-medium hover:underline"
                  >
                    {l.serviceRequested ?? "Unspecified service"}
                  </Link>
                  <p className="text-xs text-muted-foreground">
                    {l.attribution.lastTouch.source.replace(/_/g, " ")} ·{" "}
                    {l.channel.replace(/_/g, " ")} · {formatDenver(l.createdAt)}
                  </p>
                  {l.location && (
                    <p className="text-xs text-muted-foreground">
                      {l.location}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 flex-wrap items-center justify-end gap-1">
                  {attentionIds.has(l.id) && (
                    <Badge variant="destructive">needs attention</Badge>
                  )}
                  <Badge variant="secondary">
                    {l.status.replace(/_/g, " ")}
                  </Badge>
                  <Badge variant="outline">score {l.score}</Badge>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
