/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JarvisRouteImport } from './routes/jarvis'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations.index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles.new'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as SuppliersPartsRouteImport } from './routes/suppliers.parts'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsModulesRouteImport } from './routes/settings.modules'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes.$quoteId'
import { Route as PartsNewRouteImport } from './routes/parts.new'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'
import { Route as MarketingPerformanceRouteImport } from './routes/marketing.performance'
import { Route as MarketingActionsRouteImport } from './routes/marketing.actions'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as KnowledgeNewRouteImport } from './routes/knowledge.new'
import { Route as KnowledgeKnowledgeIdRouteImport } from './routes/knowledge.$knowledgeId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as InspectionsNewRouteImport } from './routes/inspections.new'
import { Route as InspectionsInspectionIdRouteImport } from './routes/inspections.$inspectionId'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as ConversationsNewRouteImport } from './routes/conversations.new'
import { Route as ConversationsConversationIdRouteImport } from './routes/conversations.$conversationId'
import { Route as VehiclesVehicleIdIndexRouteImport } from './routes/vehicles.$vehicleId.index'
import { Route as TemplatesInspectionsIndexRouteImport } from './routes/templates.inspections.index'
import { Route as QuotesQuoteIdIndexRouteImport } from './routes/quotes.$quoteId.index'
import { Route as PurchasesPartsIndexRouteImport } from './routes/purchases.parts.index'
import { Route as PartsPartIdIndexRouteImport } from './routes/parts.$partId.index'
import { Route as KnowledgeKnowledgeIdIndexRouteImport } from './routes/knowledge.$knowledgeId.index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as InvoicesInvoiceIdIndexRouteImport } from './routes/invoices.$invoiceId.index'
import { Route as InspectionsInspectionIdIndexRouteImport } from './routes/inspections.$inspectionId.index'
import { Route as CustomersCustomerIdIndexRouteImport } from './routes/customers.$customerId.index'
import { Route as VehiclesVehicleIdEditRouteImport } from './routes/vehicles.$vehicleId.edit'
import { Route as TemplatesInspectionsNewRouteImport } from './routes/templates.inspections.new'
import { Route as QuotesQuoteIdEditRouteImport } from './routes/quotes.$quoteId.edit'
import { Route as PurchasesPartsNewRouteImport } from './routes/purchases.parts.new'
import { Route as PurchasesPartsPurchaseIdRouteImport } from './routes/purchases.parts.$purchaseId'
import { Route as PartsPartIdEditRouteImport } from './routes/parts.$partId.edit'
import { Route as KnowledgeKnowledgeIdEditRouteImport } from './routes/knowledge.$knowledgeId.edit'
import { Route as JobsJobIdEditRouteImport } from './routes/jobs.$jobId.edit'
import { Route as InvoicesInvoiceIdEditRouteImport } from './routes/invoices.$invoiceId.edit'
import { Route as InspectionsInspectionIdEditRouteImport } from './routes/inspections.$inspectionId.edit'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers.$customerId.edit'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JarvisRoute = JarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRoute,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesRoute,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectionsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConversationsRoute,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VehiclesRoute,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VehiclesRoute,
} as any)
const SuppliersPartsRoute = SuppliersPartsRouteImport.update({
  id: '/suppliers/parts',
  path: '/suppliers/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModulesRoute = SettingsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RequestsRoute,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const PartsNewRoute = PartsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PartsRoute,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/$partId',
  path: '/$partId',
  getParentRoute: () => PartsRoute,
} as any)
const MarketingPerformanceRoute = MarketingPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingActionsRoute = MarketingActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => MarketingRoute,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const KnowledgeNewRoute = KnowledgeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeKnowledgeIdRoute = KnowledgeKnowledgeIdRouteImport.update({
  id: '/$knowledgeId',
  path: '/$knowledgeId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const InspectionsNewRoute = InspectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InspectionsRoute,
} as any)
const InspectionsInspectionIdRoute = InspectionsInspectionIdRouteImport.update({
  id: '/$inspectionId',
  path: '/$inspectionId',
  getParentRoute: () => InspectionsRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const ConversationsNewRoute = ConversationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConversationsRoute,
} as any)
const ConversationsConversationIdRoute =
  ConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ConversationsRoute,
  } as any)
const VehiclesVehicleIdIndexRoute = VehiclesVehicleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesVehicleIdRoute,
} as any)
const TemplatesInspectionsIndexRoute =
  TemplatesInspectionsIndexRouteImport.update({
    id: '/templates/inspections/',
    path: '/templates/inspections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuotesQuoteIdIndexRoute = QuotesQuoteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesQuoteIdRoute,
} as any)
const PurchasesPartsIndexRoute = PurchasesPartsIndexRouteImport.update({
  id: '/purchases/parts/',
  path: '/purchases/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdIndexRoute = PartsPartIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsPartIdRoute,
} as any)
const KnowledgeKnowledgeIdIndexRoute =
  KnowledgeKnowledgeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => KnowledgeKnowledgeIdRoute,
  } as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const InvoicesInvoiceIdIndexRoute = InvoicesInvoiceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesInvoiceIdRoute,
} as any)
const InspectionsInspectionIdIndexRoute =
  InspectionsInspectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InspectionsInspectionIdRoute,
  } as any)
const CustomersCustomerIdIndexRoute =
  CustomersCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomersCustomerIdRoute,
  } as any)
const VehiclesVehicleIdEditRoute = VehiclesVehicleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VehiclesVehicleIdRoute,
} as any)
const TemplatesInspectionsNewRoute = TemplatesInspectionsNewRouteImport.update({
  id: '/templates/inspections/new',
  path: '/templates/inspections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdEditRoute = QuotesQuoteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuotesQuoteIdRoute,
} as any)
const PurchasesPartsNewRoute = PurchasesPartsNewRouteImport.update({
  id: '/purchases/parts/new',
  path: '/purchases/parts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPartsPurchaseIdRoute =
  PurchasesPartsPurchaseIdRouteImport.update({
    id: '/purchases/parts/$purchaseId',
    path: '/purchases/parts/$purchaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartsPartIdEditRoute = PartsPartIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PartsPartIdRoute,
} as any)
const KnowledgeKnowledgeIdEditRoute =
  KnowledgeKnowledgeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => KnowledgeKnowledgeIdRoute,
  } as any)
const JobsJobIdEditRoute = JobsJobIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const InvoicesInvoiceIdEditRoute = InvoicesInvoiceIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesInvoiceIdRoute,
} as any)
const InspectionsInspectionIdEditRoute =
  InspectionsInspectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => InspectionsInspectionIdRoute,
  } as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersCustomerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/inspections': typeof InspectionsRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/jarvis': typeof JarvisRoute
  '/jobs': typeof JobsRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/marketing': typeof MarketingRouteWithChildren
  '/parts': typeof PartsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRouteWithChildren
  '/inspections/new': typeof InspectionsNewRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdRouteWithChildren
  '/knowledge/new': typeof KnowledgeNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/parts/$partId': typeof PartsPartIdRouteWithChildren
  '/parts/new': typeof PartsNewRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/suppliers/parts': typeof SuppliersPartsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/inspections/$inspectionId/edit': typeof InspectionsInspectionIdEditRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/knowledge/$knowledgeId/edit': typeof KnowledgeKnowledgeIdEditRoute
  '/parts/$partId/edit': typeof PartsPartIdEditRoute
  '/purchases/parts/$purchaseId': typeof PurchasesPartsPurchaseIdRoute
  '/purchases/parts/new': typeof PurchasesPartsNewRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/templates/inspections/new': typeof TemplatesInspectionsNewRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/inspections/$inspectionId/': typeof InspectionsInspectionIdIndexRoute
  '/invoices/$invoiceId/': typeof InvoicesInvoiceIdIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/knowledge/$knowledgeId/': typeof KnowledgeKnowledgeIdIndexRoute
  '/parts/$partId/': typeof PartsPartIdIndexRoute
  '/purchases/parts/': typeof PurchasesPartsIndexRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
  '/templates/inspections/': typeof TemplatesInspectionsIndexRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/jarvis': typeof JarvisRoute
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/inspections/new': typeof InspectionsNewRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/new': typeof JobsNewRoute
  '/knowledge/new': typeof KnowledgeNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/parts/new': typeof PartsNewRoute
  '/quotes/new': typeof QuotesNewRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/suppliers/parts': typeof SuppliersPartsRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/conversations': typeof ConversationsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/parts': typeof PartsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/inspections/$inspectionId/edit': typeof InspectionsInspectionIdEditRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/knowledge/$knowledgeId/edit': typeof KnowledgeKnowledgeIdEditRoute
  '/parts/$partId/edit': typeof PartsPartIdEditRoute
  '/purchases/parts/$purchaseId': typeof PurchasesPartsPurchaseIdRoute
  '/purchases/parts/new': typeof PurchasesPartsNewRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/templates/inspections/new': typeof TemplatesInspectionsNewRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId': typeof CustomersCustomerIdIndexRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdIndexRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdIndexRoute
  '/parts/$partId': typeof PartsPartIdIndexRoute
  '/purchases/parts': typeof PurchasesPartsIndexRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdIndexRoute
  '/templates/inspections': typeof TemplatesInspectionsIndexRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/inspections': typeof InspectionsRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/jarvis': typeof JarvisRoute
  '/jobs': typeof JobsRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/marketing': typeof MarketingRouteWithChildren
  '/parts': typeof PartsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/requests': typeof RequestsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/vehicles': typeof VehiclesRouteWithChildren
  '/conversations/$conversationId': typeof ConversationsConversationIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/$customerId': typeof CustomersCustomerIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRouteWithChildren
  '/inspections/new': typeof InspectionsNewRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdRouteWithChildren
  '/knowledge/new': typeof KnowledgeNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/parts/$partId': typeof PartsPartIdRouteWithChildren
  '/parts/new': typeof PartsNewRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
  '/requests/new': typeof RequestsNewRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/suppliers/parts': typeof SuppliersPartsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/inspections/$inspectionId/edit': typeof InspectionsInspectionIdEditRoute
  '/invoices/$invoiceId/edit': typeof InvoicesInvoiceIdEditRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/knowledge/$knowledgeId/edit': typeof KnowledgeKnowledgeIdEditRoute
  '/parts/$partId/edit': typeof PartsPartIdEditRoute
  '/purchases/parts/$purchaseId': typeof PurchasesPartsPurchaseIdRoute
  '/purchases/parts/new': typeof PurchasesPartsNewRoute
  '/quotes/$quoteId/edit': typeof QuotesQuoteIdEditRoute
  '/templates/inspections/new': typeof TemplatesInspectionsNewRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/inspections/$inspectionId/': typeof InspectionsInspectionIdIndexRoute
  '/invoices/$invoiceId/': typeof InvoicesInvoiceIdIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/knowledge/$knowledgeId/': typeof KnowledgeKnowledgeIdIndexRoute
  '/parts/$partId/': typeof PartsPartIdIndexRoute
  '/purchases/parts/': typeof PurchasesPartsIndexRoute
  '/quotes/$quoteId/': typeof QuotesQuoteIdIndexRoute
  '/templates/inspections/': typeof TemplatesInspectionsIndexRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/conversations'
    | '/customers'
    | '/inspections'
    | '/invoices'
    | '/jarvis'
    | '/jobs'
    | '/knowledge'
    | '/leads'
    | '/marketing'
    | '/parts'
    | '/quotes'
    | '/requests'
    | '/settings'
    | '/vehicles'
    | '/conversations/$conversationId'
    | '/conversations/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/inspections/$inspectionId'
    | '/inspections/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/knowledge/$knowledgeId'
    | '/knowledge/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/marketing/actions'
    | '/marketing/performance'
    | '/parts/$partId'
    | '/parts/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/requests/new'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/modules'
    | '/settings/profile'
    | '/suppliers/parts'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/conversations/'
    | '/customers/'
    | '/inspections/'
    | '/invoices/'
    | '/jobs/'
    | '/knowledge/'
    | '/leads/'
    | '/marketing/'
    | '/parts/'
    | '/quotes/'
    | '/requests/'
    | '/settings/'
    | '/vehicles/'
    | '/customers/$customerId/edit'
    | '/inspections/$inspectionId/edit'
    | '/invoices/$invoiceId/edit'
    | '/jobs/$jobId/edit'
    | '/knowledge/$knowledgeId/edit'
    | '/parts/$partId/edit'
    | '/purchases/parts/$purchaseId'
    | '/purchases/parts/new'
    | '/quotes/$quoteId/edit'
    | '/templates/inspections/new'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId/'
    | '/inspections/$inspectionId/'
    | '/invoices/$invoiceId/'
    | '/jobs/$jobId/'
    | '/knowledge/$knowledgeId/'
    | '/parts/$partId/'
    | '/purchases/parts/'
    | '/quotes/$quoteId/'
    | '/templates/inspections/'
    | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/jarvis'
    | '/conversations/$conversationId'
    | '/conversations/new'
    | '/customers/new'
    | '/inspections/new'
    | '/invoices/new'
    | '/jobs/new'
    | '/knowledge/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/marketing/actions'
    | '/marketing/performance'
    | '/parts/new'
    | '/quotes/new'
    | '/requests/new'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/modules'
    | '/settings/profile'
    | '/suppliers/parts'
    | '/vehicles/new'
    | '/conversations'
    | '/customers'
    | '/inspections'
    | '/invoices'
    | '/jobs'
    | '/knowledge'
    | '/leads'
    | '/marketing'
    | '/parts'
    | '/quotes'
    | '/requests'
    | '/settings'
    | '/vehicles'
    | '/customers/$customerId/edit'
    | '/inspections/$inspectionId/edit'
    | '/invoices/$invoiceId/edit'
    | '/jobs/$jobId/edit'
    | '/knowledge/$knowledgeId/edit'
    | '/parts/$partId/edit'
    | '/purchases/parts/$purchaseId'
    | '/purchases/parts/new'
    | '/quotes/$quoteId/edit'
    | '/templates/inspections/new'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId'
    | '/inspections/$inspectionId'
    | '/invoices/$invoiceId'
    | '/jobs/$jobId'
    | '/knowledge/$knowledgeId'
    | '/parts/$partId'
    | '/purchases/parts'
    | '/quotes/$quoteId'
    | '/templates/inspections'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/conversations'
    | '/customers'
    | '/inspections'
    | '/invoices'
    | '/jarvis'
    | '/jobs'
    | '/knowledge'
    | '/leads'
    | '/marketing'
    | '/parts'
    | '/quotes'
    | '/requests'
    | '/settings'
    | '/vehicles'
    | '/conversations/$conversationId'
    | '/conversations/new'
    | '/customers/$customerId'
    | '/customers/new'
    | '/inspections/$inspectionId'
    | '/inspections/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/knowledge/$knowledgeId'
    | '/knowledge/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/marketing/actions'
    | '/marketing/performance'
    | '/parts/$partId'
    | '/parts/new'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/requests/new'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/modules'
    | '/settings/profile'
    | '/suppliers/parts'
    | '/vehicles/$vehicleId'
    | '/vehicles/new'
    | '/conversations/'
    | '/customers/'
    | '/inspections/'
    | '/invoices/'
    | '/jobs/'
    | '/knowledge/'
    | '/leads/'
    | '/marketing/'
    | '/parts/'
    | '/quotes/'
    | '/requests/'
    | '/settings/'
    | '/vehicles/'
    | '/customers/$customerId/edit'
    | '/inspections/$inspectionId/edit'
    | '/invoices/$invoiceId/edit'
    | '/jobs/$jobId/edit'
    | '/knowledge/$knowledgeId/edit'
    | '/parts/$partId/edit'
    | '/purchases/parts/$purchaseId'
    | '/purchases/parts/new'
    | '/quotes/$quoteId/edit'
    | '/templates/inspections/new'
    | '/vehicles/$vehicleId/edit'
    | '/customers/$customerId/'
    | '/inspections/$inspectionId/'
    | '/invoices/$invoiceId/'
    | '/jobs/$jobId/'
    | '/knowledge/$knowledgeId/'
    | '/parts/$partId/'
    | '/purchases/parts/'
    | '/quotes/$quoteId/'
    | '/templates/inspections/'
    | '/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  InspectionsRoute: typeof InspectionsRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  JarvisRoute: typeof JarvisRoute
  JobsRoute: typeof JobsRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LeadsRoute: typeof LeadsRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  PartsRoute: typeof PartsRouteWithChildren
  QuotesRoute: typeof QuotesRouteWithChildren
  RequestsRoute: typeof RequestsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  VehiclesRoute: typeof VehiclesRouteWithChildren
  SuppliersPartsRoute: typeof SuppliersPartsRoute
  PurchasesPartsPurchaseIdRoute: typeof PurchasesPartsPurchaseIdRoute
  PurchasesPartsNewRoute: typeof PurchasesPartsNewRoute
  TemplatesInspectionsNewRoute: typeof TemplatesInspectionsNewRoute
  PurchasesPartsIndexRoute: typeof PurchasesPartsIndexRoute
  TemplatesInspectionsIndexRoute: typeof TemplatesInspectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarvis': {
      id: '/jarvis'
      path: '/jarvis'
      fullPath: '/jarvis'
      preLoaderRoute: typeof JarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/suppliers/parts': {
      id: '/suppliers/parts'
      path: '/suppliers/parts'
      fullPath: '/suppliers/parts'
      preLoaderRoute: typeof SuppliersPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/modules': {
      id: '/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof SettingsModulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/parts/new': {
      id: '/parts/new'
      path: '/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof PartsNewRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof PartsRoute
    }
    '/marketing/performance': {
      id: '/marketing/performance'
      path: '/performance'
      fullPath: '/marketing/performance'
      preLoaderRoute: typeof MarketingPerformanceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/actions': {
      id: '/marketing/actions'
      path: '/actions'
      fullPath: '/marketing/actions'
      preLoaderRoute: typeof MarketingActionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/knowledge/new': {
      id: '/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof KnowledgeNewRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$knowledgeId': {
      id: '/knowledge/$knowledgeId'
      path: '/$knowledgeId'
      fullPath: '/knowledge/$knowledgeId'
      preLoaderRoute: typeof KnowledgeKnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/inspections/new': {
      id: '/inspections/new'
      path: '/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof InspectionsNewRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/inspections/$inspectionId': {
      id: '/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/inspections/$inspectionId'
      preLoaderRoute: typeof InspectionsInspectionIdRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/conversations/new': {
      id: '/conversations/new'
      path: '/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof ConversationsNewRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/conversations/$conversationId': {
      id: '/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof ConversationsConversationIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/vehicles/$vehicleId/': {
      id: '/vehicles/$vehicleId/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof VehiclesVehicleIdIndexRouteImport
      parentRoute: typeof VehiclesVehicleIdRoute
    }
    '/templates/inspections/': {
      id: '/templates/inspections/'
      path: '/templates/inspections'
      fullPath: '/templates/inspections/'
      preLoaderRoute: typeof TemplatesInspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId/': {
      id: '/quotes/$quoteId/'
      path: '/'
      fullPath: '/quotes/$quoteId/'
      preLoaderRoute: typeof QuotesQuoteIdIndexRouteImport
      parentRoute: typeof QuotesQuoteIdRoute
    }
    '/purchases/parts/': {
      id: '/purchases/parts/'
      path: '/purchases/parts'
      fullPath: '/purchases/parts/'
      preLoaderRoute: typeof PurchasesPartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId/': {
      id: '/parts/$partId/'
      path: '/'
      fullPath: '/parts/$partId/'
      preLoaderRoute: typeof PartsPartIdIndexRouteImport
      parentRoute: typeof PartsPartIdRoute
    }
    '/knowledge/$knowledgeId/': {
      id: '/knowledge/$knowledgeId/'
      path: '/'
      fullPath: '/knowledge/$knowledgeId/'
      preLoaderRoute: typeof KnowledgeKnowledgeIdIndexRouteImport
      parentRoute: typeof KnowledgeKnowledgeIdRoute
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/invoices/$invoiceId/': {
      id: '/invoices/$invoiceId/'
      path: '/'
      fullPath: '/invoices/$invoiceId/'
      preLoaderRoute: typeof InvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof InvoicesInvoiceIdRoute
    }
    '/inspections/$inspectionId/': {
      id: '/inspections/$inspectionId/'
      path: '/'
      fullPath: '/inspections/$inspectionId/'
      preLoaderRoute: typeof InspectionsInspectionIdIndexRouteImport
      parentRoute: typeof InspectionsInspectionIdRoute
    }
    '/customers/$customerId/': {
      id: '/customers/$customerId/'
      path: '/'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof CustomersCustomerIdIndexRouteImport
      parentRoute: typeof CustomersCustomerIdRoute
    }
    '/vehicles/$vehicleId/edit': {
      id: '/vehicles/$vehicleId/edit'
      path: '/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof VehiclesVehicleIdEditRouteImport
      parentRoute: typeof VehiclesVehicleIdRoute
    }
    '/templates/inspections/new': {
      id: '/templates/inspections/new'
      path: '/templates/inspections/new'
      fullPath: '/templates/inspections/new'
      preLoaderRoute: typeof TemplatesInspectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$quoteId/edit': {
      id: '/quotes/$quoteId/edit'
      path: '/edit'
      fullPath: '/quotes/$quoteId/edit'
      preLoaderRoute: typeof QuotesQuoteIdEditRouteImport
      parentRoute: typeof QuotesQuoteIdRoute
    }
    '/purchases/parts/new': {
      id: '/purchases/parts/new'
      path: '/purchases/parts/new'
      fullPath: '/purchases/parts/new'
      preLoaderRoute: typeof PurchasesPartsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/parts/$purchaseId': {
      id: '/purchases/parts/$purchaseId'
      path: '/purchases/parts/$purchaseId'
      fullPath: '/purchases/parts/$purchaseId'
      preLoaderRoute: typeof PurchasesPartsPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId/edit': {
      id: '/parts/$partId/edit'
      path: '/edit'
      fullPath: '/parts/$partId/edit'
      preLoaderRoute: typeof PartsPartIdEditRouteImport
      parentRoute: typeof PartsPartIdRoute
    }
    '/knowledge/$knowledgeId/edit': {
      id: '/knowledge/$knowledgeId/edit'
      path: '/edit'
      fullPath: '/knowledge/$knowledgeId/edit'
      preLoaderRoute: typeof KnowledgeKnowledgeIdEditRouteImport
      parentRoute: typeof KnowledgeKnowledgeIdRoute
    }
    '/jobs/$jobId/edit': {
      id: '/jobs/$jobId/edit'
      path: '/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof JobsJobIdEditRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/invoices/$invoiceId/edit': {
      id: '/invoices/$invoiceId/edit'
      path: '/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof InvoicesInvoiceIdEditRouteImport
      parentRoute: typeof InvoicesInvoiceIdRoute
    }
    '/inspections/$inspectionId/edit': {
      id: '/inspections/$inspectionId/edit'
      path: '/edit'
      fullPath: '/inspections/$inspectionId/edit'
      preLoaderRoute: typeof InspectionsInspectionIdEditRouteImport
      parentRoute: typeof InspectionsInspectionIdRoute
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof CustomersCustomerIdRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsConversationIdRoute: typeof ConversationsConversationIdRoute
  ConversationsNewRoute: typeof ConversationsNewRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsConversationIdRoute: ConversationsConversationIdRoute,
  ConversationsNewRoute: ConversationsNewRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

interface CustomersCustomerIdRouteChildren {
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  CustomersCustomerIdIndexRoute: typeof CustomersCustomerIdIndexRoute
}

const CustomersCustomerIdRouteChildren: CustomersCustomerIdRouteChildren = {
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  CustomersCustomerIdIndexRoute: CustomersCustomerIdIndexRoute,
}

const CustomersCustomerIdRouteWithChildren =
  CustomersCustomerIdRoute._addFileChildren(CustomersCustomerIdRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InspectionsInspectionIdRouteChildren {
  InspectionsInspectionIdEditRoute: typeof InspectionsInspectionIdEditRoute
  InspectionsInspectionIdIndexRoute: typeof InspectionsInspectionIdIndexRoute
}

const InspectionsInspectionIdRouteChildren: InspectionsInspectionIdRouteChildren =
  {
    InspectionsInspectionIdEditRoute: InspectionsInspectionIdEditRoute,
    InspectionsInspectionIdIndexRoute: InspectionsInspectionIdIndexRoute,
  }

const InspectionsInspectionIdRouteWithChildren =
  InspectionsInspectionIdRoute._addFileChildren(
    InspectionsInspectionIdRouteChildren,
  )

interface InspectionsRouteChildren {
  InspectionsInspectionIdRoute: typeof InspectionsInspectionIdRouteWithChildren
  InspectionsNewRoute: typeof InspectionsNewRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
}

const InspectionsRouteChildren: InspectionsRouteChildren = {
  InspectionsInspectionIdRoute: InspectionsInspectionIdRouteWithChildren,
  InspectionsNewRoute: InspectionsNewRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
}

const InspectionsRouteWithChildren = InspectionsRoute._addFileChildren(
  InspectionsRouteChildren,
)

interface InvoicesInvoiceIdRouteChildren {
  InvoicesInvoiceIdEditRoute: typeof InvoicesInvoiceIdEditRoute
  InvoicesInvoiceIdIndexRoute: typeof InvoicesInvoiceIdIndexRoute
}

const InvoicesInvoiceIdRouteChildren: InvoicesInvoiceIdRouteChildren = {
  InvoicesInvoiceIdEditRoute: InvoicesInvoiceIdEditRoute,
  InvoicesInvoiceIdIndexRoute: InvoicesInvoiceIdIndexRoute,
}

const InvoicesInvoiceIdRouteWithChildren =
  InvoicesInvoiceIdRoute._addFileChildren(InvoicesInvoiceIdRouteChildren)

interface InvoicesRouteChildren {
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface JobsJobIdRouteChildren {
  JobsJobIdEditRoute: typeof JobsJobIdEditRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdEditRoute: JobsJobIdEditRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface KnowledgeKnowledgeIdRouteChildren {
  KnowledgeKnowledgeIdEditRoute: typeof KnowledgeKnowledgeIdEditRoute
  KnowledgeKnowledgeIdIndexRoute: typeof KnowledgeKnowledgeIdIndexRoute
}

const KnowledgeKnowledgeIdRouteChildren: KnowledgeKnowledgeIdRouteChildren = {
  KnowledgeKnowledgeIdEditRoute: KnowledgeKnowledgeIdEditRoute,
  KnowledgeKnowledgeIdIndexRoute: KnowledgeKnowledgeIdIndexRoute,
}

const KnowledgeKnowledgeIdRouteWithChildren =
  KnowledgeKnowledgeIdRoute._addFileChildren(KnowledgeKnowledgeIdRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeKnowledgeIdRoute: typeof KnowledgeKnowledgeIdRouteWithChildren
  KnowledgeNewRoute: typeof KnowledgeNewRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeKnowledgeIdRoute: KnowledgeKnowledgeIdRouteWithChildren,
  KnowledgeNewRoute: KnowledgeNewRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface MarketingRouteChildren {
  MarketingActionsRoute: typeof MarketingActionsRoute
  MarketingPerformanceRoute: typeof MarketingPerformanceRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingActionsRoute: MarketingActionsRoute,
  MarketingPerformanceRoute: MarketingPerformanceRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PartsPartIdRouteChildren {
  PartsPartIdEditRoute: typeof PartsPartIdEditRoute
  PartsPartIdIndexRoute: typeof PartsPartIdIndexRoute
}

const PartsPartIdRouteChildren: PartsPartIdRouteChildren = {
  PartsPartIdEditRoute: PartsPartIdEditRoute,
  PartsPartIdIndexRoute: PartsPartIdIndexRoute,
}

const PartsPartIdRouteWithChildren = PartsPartIdRoute._addFileChildren(
  PartsPartIdRouteChildren,
)

interface PartsRouteChildren {
  PartsPartIdRoute: typeof PartsPartIdRouteWithChildren
  PartsNewRoute: typeof PartsNewRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsPartIdRoute: PartsPartIdRouteWithChildren,
  PartsNewRoute: PartsNewRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

interface QuotesQuoteIdRouteChildren {
  QuotesQuoteIdEditRoute: typeof QuotesQuoteIdEditRoute
  QuotesQuoteIdIndexRoute: typeof QuotesQuoteIdIndexRoute
}

const QuotesQuoteIdRouteChildren: QuotesQuoteIdRouteChildren = {
  QuotesQuoteIdEditRoute: QuotesQuoteIdEditRoute,
  QuotesQuoteIdIndexRoute: QuotesQuoteIdIndexRoute,
}

const QuotesQuoteIdRouteWithChildren = QuotesQuoteIdRoute._addFileChildren(
  QuotesQuoteIdRouteChildren,
)

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRouteWithChildren
  QuotesNewRoute: typeof QuotesNewRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRouteWithChildren,
  QuotesNewRoute: QuotesNewRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface RequestsRouteChildren {
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsModulesRoute: typeof SettingsModulesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsModulesRoute: SettingsModulesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface VehiclesVehicleIdRouteChildren {
  VehiclesVehicleIdEditRoute: typeof VehiclesVehicleIdEditRoute
  VehiclesVehicleIdIndexRoute: typeof VehiclesVehicleIdIndexRoute
}

const VehiclesVehicleIdRouteChildren: VehiclesVehicleIdRouteChildren = {
  VehiclesVehicleIdEditRoute: VehiclesVehicleIdEditRoute,
  VehiclesVehicleIdIndexRoute: VehiclesVehicleIdIndexRoute,
}

const VehiclesVehicleIdRouteWithChildren =
  VehiclesVehicleIdRoute._addFileChildren(VehiclesVehicleIdRouteChildren)

interface VehiclesRouteChildren {
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRouteWithChildren
  VehiclesNewRoute: typeof VehiclesNewRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehicleIdRoute: VehiclesVehicleIdRouteWithChildren,
  VehiclesNewRoute: VehiclesNewRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  InspectionsRoute: InspectionsRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  JarvisRoute: JarvisRoute,
  JobsRoute: JobsRouteWithChildren,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LeadsRoute: LeadsRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  PartsRoute: PartsRouteWithChildren,
  QuotesRoute: QuotesRouteWithChildren,
  RequestsRoute: RequestsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  VehiclesRoute: VehiclesRouteWithChildren,
  SuppliersPartsRoute: SuppliersPartsRoute,
  PurchasesPartsPurchaseIdRoute: PurchasesPartsPurchaseIdRoute,
  PurchasesPartsNewRoute: PurchasesPartsNewRoute,
  TemplatesInspectionsNewRoute: TemplatesInspectionsNewRoute,
  PurchasesPartsIndexRoute: PurchasesPartsIndexRoute,
  TemplatesInspectionsIndexRoute: TemplatesInspectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
